// frontend/src/features/Tracks/TrackEffectRows.solid.tsx
import { createMemo, createSignal, For, Show } from "solid-js";
import { createStoreSelector } from "../../solid-utils/store";
import { createContextMenu, Icon, type ContextMenuItem } from "../../solid-ui";
import {
  EFFECT_KIND_ORDER,
  EFFECT_META,
  clampEffectParamValue,
  effectAutomationSelectionKey,
  effectValueToLaneY,
  formatEffectParamValue,
  visibleEffectAutomationPoints,
  type EffectParamMeta,
} from "../../automation/trackEffects";
import { AUTOMATION_CURVES, automationCurveLabel, evaluateAutomationCurve } from "../../automation/curves";
import { useProjectStore, useUiStore, useViewStore } from "../../state/store";
import styles from "./TrackEffectRows.module.css";
import type { Id, TrackEffect, TrackEffectAutomationPoint } from "../../state/types";

const TIMEPOINT_HANDLE_Y = 11;

interface EffectRowsProps {
  trackId: Id;
  expandedEffectIds: Set<Id>;
  onToggleEffect: (effectId: Id) => void;
}

export function TrackEffectHeaderRows(props: EffectRowsProps) {
  const track = createStoreSelector(useProjectStore, (state) => state.project.tracks.find((candidate) => candidate.id === props.trackId));
  return (
    <Show when={track()?.effects.filters.length}>
      <For each={track()?.effects.filters ?? []}>
        {(effect) => (
          <EffectRowGroupHeader
            trackId={props.trackId}
            effect={effect}
            expanded={props.expandedEffectIds.has(effect.id)}
            onToggle={() => props.onToggleEffect(effect.id)}
          />
        )}
      </For>
    </Show>
  );
}

export function TrackEffectLaneRows(props: EffectRowsProps) {
  const track = createStoreSelector(useProjectStore, (state) => state.project.tracks.find((candidate) => candidate.id === props.trackId));
  const lengthBeats = createStoreSelector(useProjectStore, (state) => state.project.lengthBeats);
  const bpm = createStoreSelector(useProjectStore, (state) => state.project.bpm);
  const beatsToPx = createStoreSelector(useViewStore, (state) => state.beatsToPx);

  return (
    <Show when={track()?.effects.filters.length}>
      <For each={track()?.effects.filters ?? []}>
        {(effect) => (
          <EffectRowGroupLane
            trackId={props.trackId}
            effect={effect}
            expanded={props.expandedEffectIds.has(effect.id)}
            onToggle={() => props.onToggleEffect(effect.id)}
            lengthBeats={lengthBeats()}
            bpm={bpm()}
            beatsToPx={beatsToPx()}
          />
        )}
      </For>
    </Show>
  );
}

function EffectRowGroupHeader(props: {
  trackId: Id;
  effect: TrackEffect;
  expanded: boolean;
  onToggle: () => void;
}) {
  const meta = createMemo(() => EFFECT_META[props.effect.kind]);
  const menu = createContextMenu((): ContextMenuItem[] => [
    {
      label: "Change Effect...",
      icon: "ph:swap",
      submenu: EFFECT_KIND_ORDER.map((kind) => ({
        label: EFFECT_META[kind].label,
        icon: kind === props.effect.kind ? "ph:check" : undefined,
        onSelect: () => useProjectStore.getState().setTrackEffectKind(props.trackId, props.effect.id, kind),
      })),
    },
    {
      label: "Reset",
      icon: "ph:arrow-counter-clockwise",
      separatorBefore: true,
      onSelect: () => useProjectStore.getState().setTrackEffectKind(props.trackId, props.effect.id, props.effect.kind),
    },
    {
      label: "Remove",
      icon: "ph:trash",
      separatorBefore: true,
      onSelect: () => {
        const projectTrack = useProjectStore.getState().project.tracks.find((candidate) => candidate.id === props.trackId);
        if (!projectTrack) return;
        useProjectStore.getState().updateTrack(props.trackId, {
          effects: {
            ...projectTrack.effects,
            filters: projectTrack.effects.filters.filter((candidate) => candidate.id !== props.effect.id),
          },
        });
      },
    },
  ]);

  return (
    <>
      <div
        class={`${styles.effectHeader} ${props.expanded ? styles.effectHeaderExpanded : ""}`}
        onContextMenu={menu.onContextMenu}
        onClick={(event) => {
          if (event.button !== 0 || event.ctrlKey) return;
          event.stopPropagation();
          props.onToggle();
        }}
        data-track-effect-header-id={props.effect.id}
      >
        <span class={styles.effectHeaderIcon}>
          <Icon name={props.expanded ? "ph:caret-down" : "ph:caret-right"} size={12} decorative />
        </span>
        <span class={styles.effectHeaderTitle}>{props.effect.kind === "plugin" && props.effect.pluginName ? props.effect.pluginName : meta().label}</span>
        {menu.menu()}
      </div>
      <Show when={props.expanded}>
        <For each={meta().params}>
          {(param) => <ValueHeaderRow effect={props.effect} param={param} />}
        </For>
      </Show>
    </>
  );
}

function ValueHeaderRow(props: { effect: TrackEffect; param: EffectParamMeta }) {
  return (
    <div class={styles.valueHeader} data-track-effect-value-header-id={`${props.effect.id}:${props.param.key}`}>
      <span class={styles.valueHeaderIcon}>
        <Icon name="ph:arrow-elbow-down-right" size={12} decorative />
      </span>
      <span class={styles.valueHeaderTitle}>{props.param.label}</span>
      <span class={styles.valueHeaderValue}>
        {formatEffectParamValue(props.effect.params[props.param.key] ?? props.param.min, props.param)}
      </span>
    </div>
  );
}

function EffectRowGroupLane(props: {
  trackId: Id;
  effect: TrackEffect;
  expanded: boolean;
  onToggle: () => void;
  lengthBeats: number;
  bpm: number;
  beatsToPx: number;
}) {
  const meta = createMemo(() => EFFECT_META[props.effect.kind]);
  const ghostPoints = createMemo(() => meta().params.flatMap((param) =>
    visibleEffectAutomationPoints(props.effect, param, props.lengthBeats, props.bpm).map((point) => ({ point, param })),
  ));

  return (
    <>
      <EffectSummaryLane
        effect={props.effect}
        expanded={props.expanded}
        onToggle={props.onToggle}
        lengthBeats={props.lengthBeats}
        beatsToPx={props.beatsToPx}
        ghostPoints={ghostPoints()}
      />
      <Show when={props.expanded}>
        <For each={meta().params}>
          {(param) => (
            <TrackEffectValueLaneRow
              trackId={props.trackId}
              effect={props.effect}
              param={param}
              lengthBeats={props.lengthBeats}
              bpm={props.bpm}
              beatsToPx={props.beatsToPx}
            />
          )}
        </For>
      </Show>
    </>
  );
}

function EffectSummaryLane(props: {
  effect: TrackEffect;
  expanded: boolean;
  onToggle: () => void;
  lengthBeats: number;
  beatsToPx: number;
  ghostPoints: Array<{ point: TrackEffectAutomationPoint; param: EffectParamMeta }>;
}) {
  return (
    <div
      class={`${styles.effectLane} ${styles.effectSummaryLane} ${props.expanded ? styles.effectLaneExpanded : ""}`}
      style={{ width: `${props.lengthBeats * props.beatsToPx}px` }}
      onClick={(event) => {
        if (event.button !== 0 || event.ctrlKey) return;
        event.stopPropagation();
        props.onToggle();
      }}
      data-track-effect-lane-id={props.effect.id}
    >
      <BeatGrid lengthBeats={props.lengthBeats} beatsToPx={props.beatsToPx} />
      <For each={props.ghostPoints}>
        {({ point, param }) => (
          <span
            class={styles.valueGuide}
            style={{
              left: "0px",
              top: `${effectValueToLaneY(point.value, param)}px`,
              width: `${props.lengthBeats * props.beatsToPx}px`,
            }}
          />
        )}
      </For>
      <For each={props.ghostPoints}>
        {({ point, param }) => (
          <span
            class={`${styles.valueDiamond} ${styles.ghostDiamond}`}
            title={`${param.label} ${formatEffectParamValue(point.value, param)}`}
            style={{ left: `${point.beat * props.beatsToPx}px`, top: `${TIMEPOINT_HANDLE_Y}px` }}
          />
        )}
      </For>
    </div>
  );
}

function TrackEffectValueLaneRow(props: {
  trackId: Id;
  effect: TrackEffect;
  param: EffectParamMeta;
  lengthBeats: number;
  bpm: number;
  beatsToPx: number;
}) {
  let laneElement: HTMLDivElement | undefined;
  const [editor, setEditor] = createSignal<{ pointId?: Id; beat: number; value: string; left: number; top: number } | null>(null, { equals: false });
  const [pendingContextBeat, setPendingContextBeat] = createSignal(0);
  const selectedPointKeys = createStoreSelector(useUiStore, (state) => state.selectedTrackEffectAutomationPointKeys);
  const points = createMemo(() => visibleEffectAutomationPoints(props.effect, props.param, props.lengthBeats, props.bpm));
  const line = createMemo(() => points().length >= 2
    ? points().flatMap((point, index) => {
        const next = points()[index + 1];
        if (!next) return [];
        const segmentCount = (point.curve ?? "linear") === "hold" ? 1 : 8;
        return Array.from({ length: segmentCount }, (_, segmentIndex) => {
          const t = segmentIndex / segmentCount;
          const nextT = (segmentIndex + 1) / segmentCount;
          const startValue = evaluateAutomationCurve(point.curve, point.value, next.value, t);
          const endValue = evaluateAutomationCurve(point.curve, point.value, next.value, nextT);
          return {
            x: (point.beat + (next.beat - point.beat) * t) * props.beatsToPx,
            y: effectValueToLaneY(startValue, props.param),
            x2: (point.beat + (next.beat - point.beat) * nextT) * props.beatsToPx,
            y2: effectValueToLaneY(endValue, props.param),
          };
        });
      })
    : []);
  const menu = createContextMenu((): ContextMenuItem[] => [
    {
      label: "+ Timepoint",
      icon: "ph:diamond",
      onSelect: () => {
        useProjectStore.getState().upsertTrackEffectAutomationPoint(props.trackId, props.effect.id, props.param.key, {
          beat: pendingContextBeat(),
          value: props.effect.params[props.param.key] ?? props.param.min,
          curve: "linear",
        });
      },
    },
  ]);

  function beatAtClientX(clientX: number, target: HTMLElement): number {
    const rect = target.getBoundingClientRect();
    return Math.max(0, Math.min(props.lengthBeats, (clientX - rect.left) / props.beatsToPx));
  }

  function beatAtLaneClientX(clientX: number): number {
    if (!laneElement) return 0;
    return beatAtClientX(clientX, laneElement);
  }

  function openEditor(beat: number, fallbackValue: number, pointId?: Id) {
    setEditor({
      pointId,
      beat,
      value: String(Math.round(fallbackValue * 100) / 100),
      left: beat * props.beatsToPx,
      top: TIMEPOINT_HANDLE_Y,
    });
  }

  function commitEditor() {
    const current = editor();
    if (!current) return;
    const parsed = Number(current.value);
    if (!Number.isFinite(parsed)) return;
    const existingPoint = points().find((point) => point.id === current.pointId);
    useProjectStore.getState().upsertTrackEffectAutomationPoint(props.trackId, props.effect.id, props.param.key, {
      id: current.pointId,
      beat: current.beat,
      value: clampEffectParamValue(parsed, props.param),
      curve: existingPoint?.curve ?? "linear",
    });
    setEditor(null);
  }

  function movePointToClientX(pointId: Id, value: number, clientX: number) {
    const existingPoint = points().find((point) => point.id === pointId);
    useProjectStore.getState().upsertTrackEffectAutomationPoint(props.trackId, props.effect.id, props.param.key, {
      id: pointId,
      beat: beatAtLaneClientX(clientX),
      value,
      curve: existingPoint?.curve ?? "linear",
    });
  }

  function startPointDrag(point: TrackEffectAutomationPoint, clientX: number) {
    let moved = false;
    const startClientX = clientX;
    const handleMouseMove = (event: MouseEvent) => {
      if (!moved && Math.abs(event.clientX - startClientX) < 2) return;
      moved = true;
      movePointToClientX(point.id, point.value, event.clientX);
    };
    const stopDrag = () => {
      window.removeEventListener("mousemove", handleMouseMove);
      window.removeEventListener("mouseup", stopDrag);
    };
    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("mouseup", stopDrag);
  }

  return (
    <div
      ref={laneElement}
      class={`${styles.effectLane} ${styles.valueLane}`}
      style={{ width: `${props.lengthBeats * props.beatsToPx}px` }}
      onContextMenu={(event) => {
        setPendingContextBeat(beatAtClientX(event.clientX, event.currentTarget));
        menu.onContextMenu(event);
      }}
      onDblClick={(event) => {
        event.stopPropagation();
        const beat = beatAtClientX(event.clientX, event.currentTarget);
        openEditor(beat, props.effect.params[props.param.key] ?? props.param.min);
      }}
      data-track-effect-value-lane-id={`${props.effect.id}:${props.param.key}`}
    >
      <BeatGrid lengthBeats={props.lengthBeats} beatsToPx={props.beatsToPx} />
      <For each={points()}>
        {(point, index) => {
          const next = () => points()[index() + 1];
          const startX = () => index() === 0 ? 0 : point.beat * props.beatsToPx;
          const endX = () => next() ? next()!.beat * props.beatsToPx : props.lengthBeats * props.beatsToPx;
          return (
            <span
              class={styles.valueGuide}
              style={{
                left: `${startX()}px`,
                top: `${effectValueToLaneY(point.value, props.param)}px`,
                width: `${Math.max(0, endX() - startX())}px`,
              }}
            />
          );
        }}
      </For>
      <For each={line()}>
        {(segment) => {
          const dx = segment.x2 - segment.x;
          const dy = segment.y2 - segment.y;
          return (
            <span
              class={styles.valueLine}
              style={{
                left: `${segment.x}px`,
                top: `${segment.y}px`,
                width: `${Math.hypot(dx, dy)}px`,
                transform: `rotate(${Math.atan2(dy, dx)}rad)`,
                "transform-origin": "left center",
              }}
            />
          );
        }}
      </For>
      <For each={points()}>
        {(point) => {
          const pointKey = () => effectAutomationSelectionKey(props.trackId, props.effect.id, props.param.key, point.id);
          return (
            <AutomationPointDiamond
              trackId={props.trackId}
              effect={props.effect}
              param={props.param}
              point={point}
              pointKey={pointKey()}
              selected={selectedPointKeys().includes(pointKey())}
              beatsToPx={props.beatsToPx}
              onSelect={(additive) => useUiStore.getState().selectTrackEffectAutomationPoint(pointKey(), additive)}
              onStartDrag={(clientX) => {
                setEditor(null);
                startPointDrag(point, clientX);
              }}
              onOpenEditor={() => openEditor(point.beat, point.value, point.id)}
            />
          );
        }}
      </For>
      <Show when={editor()}>
        {(current) => (
          <div
            class={styles.pointPopover}
            style={{ left: `${current().left}px`, top: `${current().top}px` }}
            onDblClick={(event) => event.stopPropagation()}
            onPointerDown={(event) => event.stopPropagation()}
          >
            <input
              class={styles.pointInput}
              value={current().value}
              autofocus
              onInput={(event) => setEditor({ ...current(), value: event.currentTarget.value })}
              onBlur={commitEditor}
              onKeyDown={(event) => {
                if (event.key === "Enter") commitEditor();
                if (event.key === "Escape") setEditor(null);
              }}
            />
            <span class={styles.pointUnit}>{props.param.unit}</span>
          </div>
        )}
      </Show>
      {menu.menu()}
    </div>
  );
}

function AutomationPointDiamond(props: {
  trackId: Id;
  effect: TrackEffect;
  param: EffectParamMeta;
  point: TrackEffectAutomationPoint;
  pointKey: string;
  selected: boolean;
  beatsToPx: number;
  onSelect: (additive: boolean) => void;
  onStartDrag: (clientX: number) => void;
  onOpenEditor: () => void;
}) {
  const menu = createContextMenu((): ContextMenuItem[] => [
    {
      label: "Curve",
      icon: "ph:bezier-curve",
      submenu: AUTOMATION_CURVES.map((curve) => ({
        label: automationCurveLabel(curve),
        icon: (props.point.curve ?? "linear") === curve ? "ph:check" : undefined,
        onSelect: () => {
          useProjectStore.getState().upsertTrackEffectAutomationPoint(props.trackId, props.effect.id, props.param.key, {
            id: props.point.id,
            beat: props.point.beat,
            value: props.point.value,
            curve,
          });
        },
      })),
    },
    {
      label: "Delete",
      icon: "ph:trash",
      separatorBefore: true,
      onSelect: () => useProjectStore.getState().removeTrackEffectAutomationPoint(props.trackId, props.effect.id, props.param.key, props.point.id),
    },
  ]);

  return (
    <>
      <span
        class={`${styles.valueDiamond} ${props.selected ? styles.valueDiamondSelected : ""}`}
        title={`${props.param.label} ${formatEffectParamValue(props.point.value, props.param)} · ${automationCurveLabel(props.point.curve ?? "linear")}`}
        style={{ left: `${props.point.beat * props.beatsToPx}px`, top: `${TIMEPOINT_HANDLE_Y}px` }}
        data-track-effect-automation-point-key={props.pointKey}
        onContextMenu={(event) => {
          useUiStore.getState().selectTrackEffectAutomationPoint(props.pointKey, false);
          menu.onContextMenu(event);
        }}
        onClick={(event) => {
          event.stopPropagation();
          props.onSelect(event.shiftKey);
        }}
        onMouseDown={(event) => {
          if (event.button !== 0 || event.ctrlKey) return;
          event.stopPropagation();
          props.onStartDrag(event.clientX);
        }}
        onDblClick={(event) => {
          event.stopPropagation();
          props.onOpenEditor();
        }}
      >
        <span class={styles.valueTooltip}>{formatEffectParamValue(props.point.value, props.param)}</span>
      </span>
      {menu.menu()}
    </>
  );
}

function BeatGrid(props: { lengthBeats: number; beatsToPx: number }) {
  return (
    <For each={Array.from({ length: props.lengthBeats + 1 }, (_, beat) => beat)}>
      {(beat) => (
        <div
          class={`${styles.gridLine} ${beat % 4 === 0 ? styles.gridLineMajor : ""}`}
          style={{ left: `${beat * props.beatsToPx}px` }}
        />
      )}
    </For>
  );
}

// frontend/src/features/Tracks/TrackEffectRows.tsx
import { useRef, useState } from "react";
import { Icon, useContextMenu, type ContextMenuItem } from "../../components";
import {
  EFFECT_KIND_ORDER,
  EFFECT_META,
  clampEffectParamValue,
  effectAutomationSelectionKey,
  effectValueToLaneY,
  formatEffectParamValue,
  visibleEffectAutomationPoints,
  type EffectParamMeta,
} from "../../automation/trackEffects";
import { AUTOMATION_CURVES, automationCurveLabel, evaluateAutomationCurve } from "../../automation/curves";
import { useProjectStore, useUiStore, useViewStore } from "../../state/store";
import styles from "./TrackEffectRows.module.css";
import type { Id, TrackEffect, TrackEffectAutomationPoint } from "../../state/types";
const TIMEPOINT_HANDLE_Y = 11;

interface EffectRowsProps {
  trackId: Id;
  expandedEffectIds: Set<Id>;
  onToggleEffect: (effectId: Id) => void;
}

export function TrackEffectHeaderRows({ trackId, expandedEffectIds, onToggleEffect }: EffectRowsProps) {
  const track = useProjectStore((s) => s.project.tracks.find((candidate) => candidate.id === trackId));
  if (!track || track.effects.filters.length === 0) return null;

  return (
    <>
      {track.effects.filters.map((effect) => (
        <EffectRowGroupHeader
          key={effect.id}
          trackId={trackId}
          effect={effect}
          expanded={expandedEffectIds.has(effect.id)}
          onToggle={() => onToggleEffect(effect.id)}
        />
      ))}
    </>
  );
}

export function TrackEffectLaneRows({ trackId, expandedEffectIds, onToggleEffect }: EffectRowsProps) {
  const track = useProjectStore((s) => s.project.tracks.find((candidate) => candidate.id === trackId));
  const lengthBeats = useProjectStore((s) => s.project.lengthBeats);
  const bpm = useProjectStore((s) => s.project.bpm);
  const beatsToPx = useViewStore((s) => s.beatsToPx);
  if (!track || track.effects.filters.length === 0) return null;

  return (
    <>
      {track.effects.filters.map((effect) => (
        <EffectRowGroupLane
          key={effect.id}
          trackId={trackId}
          effect={effect}
          expanded={expandedEffectIds.has(effect.id)}
          onToggle={() => onToggleEffect(effect.id)}
          lengthBeats={lengthBeats}
          bpm={bpm}
          beatsToPx={beatsToPx}
        />
      ))}
    </>
  );
}

function EffectRowGroupHeader({
  trackId,
  effect,
  expanded,
  onToggle,
}: {
  trackId: Id;
  effect: TrackEffect;
  expanded: boolean;
  onToggle: () => void;
}) {
  const updateTrack = useProjectStore((s) => s.updateTrack);
  const setTrackEffectKind = useProjectStore((s) => s.setTrackEffectKind);
  const meta = EFFECT_META[effect.kind];

  const { onContextMenu, menu } = useContextMenu((): ContextMenuItem[] => [
    {
      label: "Change Effect...",
      icon: "ph:swap",
      submenu: EFFECT_KIND_ORDER.map((kind) => ({
        label: EFFECT_META[kind].label,
        icon: kind === effect.kind ? "ph:check" : undefined,
        onSelect: () => setTrackEffectKind(trackId, effect.id, kind),
      })),
    },
    {
      label: "Reset",
      icon: "ph:arrow-counter-clockwise",
      separatorBefore: true,
      onSelect: () => setTrackEffectKind(trackId, effect.id, effect.kind),
    },
    {
      label: "Remove",
      icon: "ph:trash",
      separatorBefore: true,
      onSelect: () => {
        const projectTrack = useProjectStore.getState().project.tracks.find((candidate) => candidate.id === trackId);
        if (!projectTrack) return;
        updateTrack(trackId, {
          effects: {
            ...projectTrack.effects,
            filters: projectTrack.effects.filters.filter((candidate) => candidate.id !== effect.id),
          },
        });
      },
    },
  ]);

  return (
    <>
      <div
        className={`${styles.effectHeader} ${expanded ? styles.effectHeaderExpanded : ""}`}
        onContextMenu={onContextMenu}
        onClick={(event) => {
          if (event.button !== 0 || event.ctrlKey) return;
          event.stopPropagation();
          onToggle();
        }}
        data-track-effect-header-id={effect.id}
      >
        <span className={styles.effectHeaderIcon}>
          <Icon name={expanded ? "ph:caret-down" : "ph:caret-right"} size={12} decorative />
        </span>
        <span className={styles.effectHeaderTitle}>{effect.kind === "plugin" && effect.pluginName ? effect.pluginName : meta.label}</span>
        {menu}
      </div>
      {expanded && meta.params.map((param) => (
        <ValueHeaderRow key={`${effect.id}:${param.key}`} effect={effect} param={param} />
      ))}
    </>
  );
}

function ValueHeaderRow({ effect, param }: { effect: TrackEffect; param: EffectParamMeta }) {
  return (
    <div className={styles.valueHeader} data-track-effect-value-header-id={`${effect.id}:${param.key}`}>
      <span className={styles.valueHeaderIcon}>
        <Icon name="ph:arrow-elbow-down-right" size={12} decorative />
      </span>
      <span className={styles.valueHeaderTitle}>{param.label}</span>
      <span className={styles.valueHeaderValue}>
        {formatEffectParamValue(effect.params[param.key] ?? param.min, param)}
      </span>
    </div>
  );
}

function EffectRowGroupLane({
  trackId,
  effect,
  expanded,
  onToggle,
  lengthBeats,
  bpm,
  beatsToPx,
}: {
  trackId: Id;
  effect: TrackEffect;
  expanded: boolean;
  onToggle: () => void;
  lengthBeats: number;
  bpm: number;
  beatsToPx: number;
}) {
  const meta = EFFECT_META[effect.kind];
  const ghostPoints = meta.params.flatMap((param) =>
    visibleEffectAutomationPoints(effect, param, lengthBeats, bpm).map((point) => ({ point, param }))
  );

  return (
    <>
      <EffectSummaryLane
        effect={effect}
        expanded={expanded}
        onToggle={onToggle}
        lengthBeats={lengthBeats}
        beatsToPx={beatsToPx}
        ghostPoints={ghostPoints}
      />
      {expanded && meta.params.map((param) => (
        <TrackEffectValueLaneRow
          key={`${effect.id}:${param.key}`}
          trackId={trackId}
          effect={effect}
          param={param}
          lengthBeats={lengthBeats}
          bpm={bpm}
          beatsToPx={beatsToPx}
        />
      ))}
    </>
  );
}

function EffectSummaryLane({
  effect,
  expanded,
  onToggle,
  lengthBeats,
  beatsToPx,
  ghostPoints,
}: {
  effect: TrackEffect;
  expanded: boolean;
  onToggle: () => void;
  lengthBeats: number;
  beatsToPx: number;
  ghostPoints: Array<{ point: TrackEffectAutomationPoint; param: EffectParamMeta }>;
}) {
  return (
    <div
      className={`${styles.effectLane} ${styles.effectSummaryLane} ${expanded ? styles.effectLaneExpanded : ""}`}
      style={{ width: lengthBeats * beatsToPx }}
      onClick={(event) => {
        if (event.button !== 0 || event.ctrlKey) return;
        event.stopPropagation();
        onToggle();
      }}
      data-track-effect-lane-id={effect.id}
    >
      <BeatGrid lengthBeats={lengthBeats} beatsToPx={beatsToPx} />
      {ghostPoints.map(({ point, param }) => (
        <span
          key={`${point.id}:${param.key}`}
          className={styles.valueGuide}
          style={{
            left: 0,
            top: effectValueToLaneY(point.value, param),
            width: lengthBeats * beatsToPx,
          }}
        />
      ))}
      {ghostPoints.map(({ point, param }) => (
        <span
          key={`${point.id}:${param.key}:ghost`}
          className={`${styles.valueDiamond} ${styles.ghostDiamond}`}
          title={`${param.label} ${formatEffectParamValue(point.value, param)}`}
          style={{ left: point.beat * beatsToPx, top: TIMEPOINT_HANDLE_Y }}
        />
      ))}
    </div>
  );
}

function TrackEffectValueLaneRow({
  trackId,
  effect,
  param,
  lengthBeats,
  bpm,
  beatsToPx,
}: {
  trackId: Id;
  effect: TrackEffect;
  param: EffectParamMeta;
  lengthBeats: number;
  bpm: number;
  beatsToPx: number;
}) {
  const laneRef = useRef<HTMLDivElement | null>(null);
  const [editor, setEditor] = useState<{
    pointId?: Id;
    beat: number;
    value: string;
    left: number;
    top: number;
  } | null>(null);
  const upsertTrackEffectAutomationPoint = useProjectStore((s) => s.upsertTrackEffectAutomationPoint);
  const selectedPointKeys = useUiStore((s) => s.selectedTrackEffectAutomationPointKeys);
  const selectTrackEffectAutomationPoint = useUiStore((s) => s.selectTrackEffectAutomationPoint);
  const points = visibleEffectAutomationPoints(effect, param, lengthBeats, bpm);
  const [pendingContextBeat, setPendingContextBeat] = useState(0);
  const { onContextMenu, menu } = useContextMenu((): ContextMenuItem[] => [
    {
      label: "+ Timepoint",
      icon: "ph:diamond",
      onSelect: () => {
        upsertTrackEffectAutomationPoint(trackId, effect.id, param.key, {
          beat: pendingContextBeat,
          value: effect.params[param.key] ?? param.min,
          curve: "linear",
        });
      },
    },
  ]);
  const line = points.length >= 2
    ? points.flatMap((point, index) => {
        const next = points[index + 1];
        if (!next) return [];
        const segmentCount = (point.curve ?? "linear") === "hold" ? 1 : 8;
        return Array.from({ length: segmentCount }, (_, segmentIndex) => {
          const t = segmentIndex / segmentCount;
          const nextT = (segmentIndex + 1) / segmentCount;
          const startValue = evaluateAutomationCurve(point.curve, point.value, next.value, t);
          const endValue = evaluateAutomationCurve(point.curve, point.value, next.value, nextT);
          return {
            x: (point.beat + (next.beat - point.beat) * t) * beatsToPx,
            y: effectValueToLaneY(startValue, param),
            x2: (point.beat + (next.beat - point.beat) * nextT) * beatsToPx,
            y2: effectValueToLaneY(endValue, param),
          };
        });
      })
    : [];

  function openEditor(beat: number, fallbackValue: number, pointId?: Id) {
    setEditor({
      pointId,
      beat,
      value: String(Math.round(fallbackValue * 100) / 100),
      left: beat * beatsToPx,
      top: TIMEPOINT_HANDLE_Y,
    });
  }

  function commitEditor() {
    if (!editor) return;
    const parsed = Number(editor.value);
    if (!Number.isFinite(parsed)) return;
    const existingPoint = points.find((point) => point.id === editor.pointId);
    upsertTrackEffectAutomationPoint(trackId, effect.id, param.key, {
      id: editor.pointId,
      beat: editor.beat,
      value: clampEffectParamValue(parsed, param),
      curve: existingPoint?.curve ?? "linear",
    });
    setEditor(null);
  }

  function beatAtClientX(clientX: number, target: HTMLElement): number {
    const rect = target.getBoundingClientRect();
    return Math.max(0, Math.min(lengthBeats, (clientX - rect.left) / beatsToPx));
  }

  function beatAtLaneClientX(clientX: number): number {
    const lane = laneRef.current;
    if (!lane) return 0;
    return beatAtClientX(clientX, lane);
  }

  function movePointToClientX(pointId: Id, value: number, clientX: number) {
    const existingPoint = points.find((point) => point.id === pointId);
    upsertTrackEffectAutomationPoint(trackId, effect.id, param.key, {
      id: pointId,
      beat: beatAtLaneClientX(clientX),
      value,
      curve: existingPoint?.curve ?? "linear",
    });
  }

  function startPointDrag(point: TrackEffectAutomationPoint, clientX: number) {
    let moved = false;
    const startClientX = clientX;
    const handleMouseMove = (event: MouseEvent) => {
      if (!moved && Math.abs(event.clientX - startClientX) < 2) return;
      moved = true;
      movePointToClientX(point.id, point.value, event.clientX);
    };
    const stopDrag = () => {
      window.removeEventListener("mousemove", handleMouseMove);
      window.removeEventListener("mouseup", stopDrag);
    };
    window.addEventListener("mousemove", handleMouseMove);
    window.addEventListener("mouseup", stopDrag);
  }

  return (
    <div
      ref={laneRef}
      className={`${styles.effectLane} ${styles.valueLane}`}
      style={{ width: lengthBeats * beatsToPx }}
      onContextMenu={(event) => {
        setPendingContextBeat(beatAtClientX(event.clientX, event.currentTarget));
        onContextMenu(event);
      }}
      onDoubleClick={(event) => {
        event.stopPropagation();
        const beat = beatAtClientX(event.clientX, event.currentTarget);
        openEditor(beat, effect.params[param.key] ?? param.min);
      }}
      data-track-effect-value-lane-id={`${effect.id}:${param.key}`}
    >
      <BeatGrid lengthBeats={lengthBeats} beatsToPx={beatsToPx} />
      {points.map((point, index) => {
        const next = points[index + 1];
        const startX = index === 0 ? 0 : point.beat * beatsToPx;
        const endX = next ? next.beat * beatsToPx : lengthBeats * beatsToPx;
        return (
          <span
            key={`${effect.id}:guide:${point.id}`}
            className={styles.valueGuide}
            style={{
              left: startX,
              top: effectValueToLaneY(point.value, param),
              width: Math.max(0, endX - startX),
            }}
          />
        );
      })}
      {line.map((segment, index) => {
        const dx = segment.x2 - segment.x;
        const dy = segment.y2 - segment.y;
        return (
          <span
            key={`${effect.id}:line:${index}`}
            className={styles.valueLine}
            style={{
              left: segment.x,
              top: segment.y,
              width: Math.hypot(dx, dy),
              transform: `rotate(${Math.atan2(dy, dx)}rad)`,
              transformOrigin: "left center",
            }}
          />
        );
      })}
      {points.map((point) => {
        const pointKey = effectAutomationSelectionKey(trackId, effect.id, param.key, point.id);
        const selected = selectedPointKeys.includes(pointKey);
        return (
          <AutomationPointDiamond
            key={point.id}
            trackId={trackId}
            effect={effect}
            param={param}
            point={point}
            pointKey={pointKey}
            selected={selected}
            beatsToPx={beatsToPx}
            onSelect={(additive) => selectTrackEffectAutomationPoint(pointKey, additive)}
            onStartDrag={(clientX) => {
              setEditor(null);
              startPointDrag(point, clientX);
            }}
            onOpenEditor={() => openEditor(point.beat, point.value, point.id)}
          />
        );
      })}
      {editor && (
        <div
          className={styles.pointPopover}
          style={{ left: editor.left, top: editor.top }}
          onDoubleClick={(event) => event.stopPropagation()}
          onPointerDown={(event) => event.stopPropagation()}
        >
          <input
            className={styles.pointInput}
            value={editor.value}
            autoFocus
            onChange={(event) => setEditor({ ...editor, value: event.target.value })}
            onBlur={commitEditor}
            onKeyDown={(event) => {
              if (event.key === "Enter") commitEditor();
              if (event.key === "Escape") setEditor(null);
            }}
          />
          <span className={styles.pointUnit}>{param.unit}</span>
        </div>
      )}
      {menu}
    </div>
  );
}

function AutomationPointDiamond({
  trackId,
  effect,
  param,
  point,
  pointKey,
  selected,
  beatsToPx,
  onSelect,
  onStartDrag,
  onOpenEditor,
}: {
  trackId: Id;
  effect: TrackEffect;
  param: EffectParamMeta;
  point: TrackEffectAutomationPoint;
  pointKey: string;
  selected: boolean;
  beatsToPx: number;
  onSelect: (additive: boolean) => void;
  onStartDrag: (clientX: number) => void;
  onOpenEditor: () => void;
}) {
  const upsertTrackEffectAutomationPoint = useProjectStore((s) => s.upsertTrackEffectAutomationPoint);
  const removeTrackEffectAutomationPoint = useProjectStore((s) => s.removeTrackEffectAutomationPoint);
  const selectTrackEffectAutomationPoint = useUiStore((s) => s.selectTrackEffectAutomationPoint);
  const { onContextMenu, menu } = useContextMenu((): ContextMenuItem[] => [
    {
      label: "Curve",
      icon: "ph:bezier-curve",
      submenu: AUTOMATION_CURVES.map((curve) => ({
        label: automationCurveLabel(curve),
        icon: (point.curve ?? "linear") === curve ? "ph:check" : undefined,
        onSelect: () => {
          upsertTrackEffectAutomationPoint(trackId, effect.id, param.key, {
            id: point.id,
            beat: point.beat,
            value: point.value,
            curve,
          });
        },
      })),
    },
    {
      label: "Delete",
      icon: "ph:trash",
      separatorBefore: true,
      onSelect: () => removeTrackEffectAutomationPoint(trackId, effect.id, param.key, point.id),
    },
  ]);

  return (
    <>
      <span
        className={`${styles.valueDiamond} ${selected ? styles.valueDiamondSelected : ""}`}
        title={`${param.label} ${formatEffectParamValue(point.value, param)} · ${automationCurveLabel(point.curve ?? "linear")}`}
        style={{ left: point.beat * beatsToPx, top: TIMEPOINT_HANDLE_Y }}
        data-track-effect-automation-point-key={pointKey}
        onContextMenu={(event) => {
          selectTrackEffectAutomationPoint(pointKey, false);
          onContextMenu(event);
        }}
        onClick={(event) => {
          event.stopPropagation();
          onSelect(event.shiftKey);
        }}
        onMouseDown={(event) => {
          if (event.button !== 0 || event.ctrlKey) return;
          event.stopPropagation();
          onStartDrag(event.clientX);
        }}
        onDoubleClick={(event) => {
          event.stopPropagation();
          onOpenEditor();
        }}
      >
        <span className={styles.valueTooltip}>{formatEffectParamValue(point.value, param)}</span>
      </span>
      {menu}
    </>
  );
}

function BeatGrid({ lengthBeats, beatsToPx }: { lengthBeats: number; beatsToPx: number }) {
  return (
    <>
      {Array.from({ length: lengthBeats + 1 }, (_, b) => (
        <div
          key={b}
          className={`${styles.gridLine} ${b % 4 === 0 ? styles.gridLineMajor : ""}`}
          style={{ left: b * beatsToPx }}
        />
      ))}
    </>
  );
}
