// frontend/src/features/PluginLibrary/DecentSamplerLibraryPanel.tsx
import { useMemo, useState } from "react";
import { HoverInfo, Icon, SectionRibbon, SectionRibbonActionButton } from "../../components";
import { usePluginStore, useUiStore } from "../../state/store";
import { PluginImportModal, PluginItem } from "./PluginLibraryPanel";
import styles from "./PluginLibraryPanel.module.css";

interface DecentSamplerLibraryPanelProps {
  expanded: boolean;
  onToggle: () => void;
}

export function DecentSamplerLibraryPanel({ expanded, onToggle }: DecentSamplerLibraryPanelProps) {
  const allPlugins = usePluginStore((s) => s.plugins);
  const plugins = useMemo(
    () => allPlugins.filter((plugin) => plugin.format === "decent-sampler"),
    [allPlugins],
  );
  const openEditor = useUiStore((s) => s.openEditor);
  const [importOpen, setImportOpen] = useState(false);

  return (
    <div className={styles.panel}>
      <SectionRibbon
        title="DecentSampler"
        expanded={expanded}
        onToggle={onToggle}
        showToggle={false}
        count={plugins.length}
        actions={
          <HoverInfo content="Import DS file">
            <SectionRibbonActionButton onClick={() => setImportOpen(true)} aria-label="Import DS file">
              <Icon name="ph:plus" size={16} decorative />
            </SectionRibbonActionButton>
          </HoverInfo>
        }
      />

      <ul className={`${styles.list} ${expanded ? styles.listOpen : ""}`} aria-hidden={!expanded}>
        {plugins.length === 0 ? (
          <li className={styles.empty}>No DecentSampler packages installed.</li>
        ) : (
          plugins.map((plugin) => (
            <PluginItem
              key={plugin.id}
              plugin={plugin}
              onOpen={() => openEditor({ kind: "plugin", pluginId: plugin.id })}
            />
          ))
        )}
      </ul>

      {importOpen && (
        <PluginImportModal
          onClose={() => setImportOpen(false)}
          onInstalled={(pluginId) => {
            setImportOpen(false);
            openEditor({ kind: "plugin", pluginId });
          }}
        />
      )}
    </div>
  );
}

// frontend/src/features/PluginLibrary/DecentSamplerLibraryPanel.solid.tsx
import { createSignal, For, Show } from "solid-js";
import { HoverInfo, Icon, SectionRibbon, SectionRibbonActionButton } from "../../solid-ui";
import { usePluginStore, useUiStore } from "../../state/store";
import { createStoreSelector } from "../../solid-utils/store";
import { PluginImportModal } from "./PluginImportModal.solid";
import { PluginItem } from "./PluginLibraryPanel.solid";
import styles from "./PluginLibraryPanel.module.css";

interface DecentSamplerLibraryPanelProps {
  expanded: boolean;
  onToggle: () => void;
}

export function DecentSamplerLibraryPanel(props: DecentSamplerLibraryPanelProps) {
  const allPlugins = createStoreSelector(usePluginStore, (s) => s.plugins);
  const plugins = () => allPlugins().filter((plugin) => plugin.format === "decent-sampler");
  const [importOpen, setImportOpen] = createSignal(false);

  return (
    <div class={styles.panel}>
      <SectionRibbon
        title="DecentSampler"
        expanded={props.expanded}
        onToggle={props.onToggle}
        showToggle={false}
        count={plugins().length}
        actions={(
          <HoverInfo content="Import DS file">
            <SectionRibbonActionButton onClick={() => setImportOpen(true)} aria-label="Import DS file">
              <Icon name="ph:plus" size={18} decorative />
            </SectionRibbonActionButton>
          </HoverInfo>
        )}
      />

      <ul class={`${styles.list} ${props.expanded ? styles.listOpen : ""}`} aria-hidden={!props.expanded}>
        <Show when={plugins().length > 0} fallback={<li class={styles.empty}>No DecentSampler packages installed.</li>}>
          <For each={plugins()}>
            {(plugin) => (
              <PluginItem
                plugin={plugin}
                onOpen={() => useUiStore.getState().openEditor({ kind: "plugin", pluginId: plugin.id })}
              />
            )}
          </For>
        </Show>
      </ul>

      <Show when={importOpen()}>
        <PluginImportModal
          onClose={() => setImportOpen(false)}
          onInstalled={(pluginId) => {
            setImportOpen(false);
            useUiStore.getState().openEditor({ kind: "plugin", pluginId });
          }}
        />
      </Show>
    </div>
  );
}
