// frontend/src/components/FloatingLayer/FloatingLayer.tsx
import { forwardRef, type CSSProperties, type ReactNode } from "react";
import styles from "./FloatingLayer.module.css";

interface FloatingLayerProps {
  x: number;
  y: number;
  width?: number;
  style?: CSSProperties;
  className?: string;
  role?: string;
  children: ReactNode;
}

export const FloatingLayer = forwardRef<HTMLDivElement, FloatingLayerProps>(function FloatingLayer(
  { x, y, width, style, className, role, children },
  ref,
) {
  return (
    <div
      ref={ref}
      className={`${styles.layer} ${className ?? ""}`}
      style={{
        "--floating-layer-x": `${x}px`,
        "--floating-layer-y": `${y}px`,
        "--floating-layer-width": width ? `${width}px` : undefined,
        ...style,
      } as CSSProperties}
      role={role}
      data-floating-layer
    >
      {children}
    </div>
  );
});

// frontend/src/solid-ui/FloatingLayer.solid.tsx
import type { JSX } from "solid-js";
import styles from "./FloatingLayer.module.css";

export interface FloatingLayerProps {
  x: number;
  y: number;
  width?: number;
  style?: JSX.CSSProperties;
  class?: string;
  className?: string;
  role?: JSX.HTMLAttributes<HTMLDivElement>["role"];
  children: JSX.Element;
  ref?: (element: HTMLDivElement) => void;
}

export function FloatingLayer(props: FloatingLayerProps) {
  return (
    <div
      ref={props.ref}
      class={`${styles.layer} ${props.class ?? props.className ?? ""}`}
      style={{
        "--floating-layer-x": `${props.x}px`,
        "--floating-layer-y": `${props.y}px`,
        "--floating-layer-width": props.width ? `${props.width}px` : undefined,
        ...props.style,
      } as JSX.CSSProperties}
      role={props.role}
      data-floating-layer
    >
      {props.children}
    </div>
  );
}
