// frontend/src/components/Toggle/Toggle.tsx
import { forwardRef } from "react";
import styles from "./Toggle.module.css";

export interface ToggleProps {
  checked: boolean;
  onChange: (v: boolean) => void;
  label?: string;
  disabled?: boolean;
  className?: string;
  labelClassName?: string;
}

/**
 * Toggle — binary on/off. Renders as a black-and-white inverting box.
 * No slide animation — color invert per design spec.
 *
 * forwardRef so HoverInfo (and other wrappers that need a DOM handle) can
 * attach refs.
 */
export const Toggle = forwardRef<HTMLLabelElement, ToggleProps>(function Toggle(
  { checked, onChange, label, disabled, className, labelClassName },
  ref,
) {
  return (
    <label ref={ref} className={[styles.wrap, className].filter(Boolean).join(" ")}>
      <button
        type="button"
        role="switch"
        aria-checked={checked}
        disabled={disabled}
        onClick={() => onChange(!checked)}
        className={`${styles.box} ${checked ? styles.on : ""}`}
      />
      {label && <span className={[styles.label, labelClassName].filter(Boolean).join(" ")}>{label}</span>}
    </label>
  );
});

// frontend/src/solid-ui/Toggle/Toggle.solid.tsx
import { Show } from "solid-js";
import styles from "./Toggle.module.css";

export interface ToggleProps {
  checked: boolean;
  onChange: (v: boolean) => void;
  label?: string;
  "aria-label"?: string;
  disabled?: boolean;
  class?: string;
  className?: string;
  labelClassName?: string;
}

export function Toggle(props: ToggleProps) {
  return (
    <label class={[styles.wrap, props.class, props.className].filter(Boolean).join(" ")}>
      <button
        type="button"
        role="switch"
        aria-checked={props.checked}
        aria-label={props["aria-label"]}
        disabled={props.disabled}
        onClick={() => props.onChange(!props.checked)}
        class={`${styles.box} ${props.checked ? styles.on : ""}`}
      />
      <Show when={props.label}>
        <span class={[styles.label, props.labelClassName].filter(Boolean).join(" ")}>{props.label}</span>
      </Show>
    </label>
  );
}
