// frontend/src/features/AudioFiles/AudioFileLibraryPanel.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { Button, HoverInfo, Icon, RowItem, SectionRibbon, SectionRibbonActionButton, appAlert, useContextMenu, type ContextMenuItem } from "../../components";
import { isSupportedAudioFileName, SUPPORTED_AUDIO_IMPORT_LABEL } from "../../audio/audioFormats";
import { importAudioFile } from "../../audio/audioImport";
import { useAudioFileStore } from "../../state/store";
import type { AudioFile } from "../../state/types";
import { ImportInstrumentModal } from "../InstrumentLibrary/ImportInstrumentModal";
import styles from "./AudioFileLibraryPanel.module.css";

interface AudioFileLibraryPanelProps {
  expanded: boolean;
  onToggle: () => void;
}

export function AudioFileLibraryPanel({ expanded, onToggle }: AudioFileLibraryPanelProps) {
  const files = useAudioFileStore((s) => s.files);
  const addFile = useAudioFileStore((s) => s.addFile);
  const removeFile = useAudioFileStore((s) => s.removeFile);
  const panelRef = useRef<HTMLDivElement>(null);
  const [selectMode, setSelectMode] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(() => new Set());
  const [lastSelectedId, setLastSelectedId] = useState<string | null>(null);
  const [groupingFiles, setGroupingFiles] = useState<AudioFile[] | null>(null);
  const selectedFiles = useMemo(
    () => files.filter((file) => selectedIds.has(file.id)),
    [files, selectedIds],
  );
  const { onContextMenu, menu } = useContextMenu((): ContextMenuItem[] => [
    {
      label: "Select",
      icon: "ph:checks",
      onSelect: () => enterSelectMode(),
    },
  ]);

  useEffect(() => {
    if (!selectMode) return;
    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") exitSelectMode();
    }
    function onPointerDown(event: PointerEvent) {
      if (panelRef.current?.contains(event.target as Node)) return;
      exitSelectMode();
    }
    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("pointerdown", onPointerDown);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("pointerdown", onPointerDown);
    };
  }, [selectMode]);

  async function upload() {
    const file = await importAudioFile();
    if (!file) return;
    if (!isSupportedAudioFileName(file.name) && !isSupportedAudioFileName(file.path)) {
      await appAlert(`Unsupported audio file. Supported formats: ${SUPPORTED_AUDIO_IMPORT_LABEL}.`);
      return;
    }
    addFile(file);
  }

  function enterSelectMode(fileId?: string) {
    setSelectMode(true);
    if (fileId) {
      setSelectedIds(new Set([fileId]));
      setLastSelectedId(fileId);
    }
  }

  function exitSelectMode() {
    setSelectMode(false);
    setSelectedIds(new Set());
    setLastSelectedId(null);
  }

  function selectFile(fileId: string, shiftKey: boolean) {
    setSelectMode(true);
    setSelectedIds((current) => {
      if (shiftKey && lastSelectedId) {
        const start = files.findIndex((file) => file.id === lastSelectedId);
        const end = files.findIndex((file) => file.id === fileId);
        if (start >= 0 && end >= 0) {
          const [lo, hi] = start < end ? [start, end] : [end, start];
          return new Set([...current, ...files.slice(lo, hi + 1).map((file) => file.id)]);
        }
      }
      const next = new Set(current);
      if (next.has(fileId)) next.delete(fileId);
      else next.add(fileId);
      return next;
    });
    setLastSelectedId(fileId);
  }

  function deleteSelected() {
    selectedFiles.forEach((file) => removeFile(file.id));
    exitSelectMode();
  }

  function groupSelected() {
    if (selectedFiles.length === 0) return;
    setGroupingFiles(selectedFiles);
  }

  return (
    <div ref={panelRef} className={styles.panel} onContextMenu={onContextMenu}>
      <SectionRibbon
        title="Audio Files"
        expanded={expanded}
        onToggle={onToggle}
        showToggle={false}
        onContextMenu={onContextMenu}
        actions={(
          <HoverInfo content={`Upload ${SUPPORTED_AUDIO_IMPORT_LABEL}`}>
            <SectionRibbonActionButton onClick={upload} aria-label="Upload audio file">
              <Icon name="ph:plus" size={16} decorative />
            </SectionRibbonActionButton>
          </HoverInfo>
        )}
      />
      {selectMode && expanded && (
        <div className={styles.selectionBar}>
          <Button size="xs" disabled={selectedFiles.length === 0} onClick={deleteSelected}>
            Delete
          </Button>
          <Button size="xs" disabled={selectedFiles.length === 0} onClick={groupSelected}>
            Group
          </Button>
          <span className={styles.selectionCount}>{selectedFiles.length}</span>
        </div>
      )}

      <ul className={`${styles.list} ${expanded ? styles.listOpen : ""}`} aria-hidden={!expanded}>
        {files.length === 0 && <li className={styles.empty}>No audio files yet.</li>}
        {files.map((file) => (
          <AudioFileItem
            key={file.id}
            file={file}
            selectMode={selectMode}
            selected={selectedIds.has(file.id)}
            onSelect={(event) => selectFile(file.id, event.shiftKey)}
            onEnterSelectMode={() => enterSelectMode(file.id)}
            onRemove={() => removeFile(file.id)}
          />
        ))}
      </ul>
      {menu}
      {groupingFiles && (
        <ImportInstrumentModal
          initialFiles={groupingFiles}
          onImportedFiles={(imported) => {
            imported.forEach((file) => removeFile(file.id));
            exitSelectMode();
          }}
          onClose={() => setGroupingFiles(null)}
        />
      )}
    </div>
  );
}

interface ItemProps {
  file: AudioFile;
  selectMode: boolean;
  selected: boolean;
  onSelect: (event: React.MouseEvent) => void;
  onEnterSelectMode: () => void;
  onRemove: () => void;
}

function AudioFileItem({ file, selectMode, selected, onSelect, onEnterSelectMode, onRemove }: ItemProps) {
  const { id, name, durationSeconds } = file;
  const { onContextMenu, menu } = useContextMenu((): ContextMenuItem[] => [
    {
      label: "Select",
      icon: "ph:checks",
      onSelect: onEnterSelectMode,
    },
    {
      label: "Delete",
      icon: "ph:trash",
      onSelect: onRemove,
      separatorBefore: true,
    },
  ]);

  function onDragStart(e: React.DragEvent<HTMLLIElement>) {
    e.dataTransfer.setData("application/x-beat-audio-file", id);
    e.dataTransfer.setData("text/plain", name);
    e.dataTransfer.effectAllowed = "copy";
  }

  return (
    <RowItem
      className={`${styles.item} ${selected ? styles.itemSelected : ""} ${selectMode ? styles.itemSelecting : ""}`}
      reserveDragSlot={false}
      cursor={selectMode ? "pointer" : "grab"}
      draggable={!selectMode}
      onClick={(event) => {
        if (!selectMode) return;
        onSelect(event);
      }}
      onDragStart={onDragStart}
      onContextMenu={onContextMenu}
      iconAriaHidden={!selectMode}
      icon={selectMode ? (
        <input
          className={styles.itemCheckbox}
          type="checkbox"
          checked={selected}
          readOnly
          onClick={(event) => {
            event.stopPropagation();
            onSelect(event);
          }}
          aria-label={`Select ${name}`}
        />
      ) : (
        <span className={styles.itemDot} aria-hidden>
          <Icon name="ph:dots-six-vertical" size={14} decorative />
        </span>
      )}
      name={name}
      action={(
        <HoverInfo content={formatDuration(durationSeconds)}>
          <span className={styles.itemMeta}>
            <Icon name="ph:waveform" size={14} decorative />
          </span>
        </HoverInfo>
      )}
    >
      {menu}
    </RowItem>
  );
}

function formatDuration(seconds: number) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

// frontend/src/features/AudioFiles/AudioFileLibraryPanel.solid.tsx
/** @jsxImportSource solid-js */
import { createEffect, createSignal, For, onCleanup, Show } from "solid-js";
import { Button, HoverInfo, Icon, RowItem, SectionRibbon, SectionRibbonActionButton, createContextMenu, type ContextMenuItem } from "../../solid-ui";
import { appAlert } from "../../components";
import { isSupportedAudioFileName, SUPPORTED_AUDIO_IMPORT_LABEL } from "../../audio/audioFormats";
import { importAudioFile } from "../../audio/audioImport";
import { useAudioFileStore } from "../../state/store";
import type { AudioFile } from "../../state/types";
import { createStoreSelector } from "../../solid-utils/store";
import { ImportInstrumentModalSolid } from "../InstrumentLibrary/ImportInstrumentModal.solid";
import styles from "./AudioFileLibraryPanel.module.css";

interface AudioFileLibraryPanelProps {
  expanded: boolean;
  onToggle: () => void;
}

export function AudioFileLibraryPanelSolid(props: AudioFileLibraryPanelProps) {
  const files = createStoreSelector(useAudioFileStore, (s) => s.files);
  const [selectMode, setSelectMode] = createSignal(false);
  const [selectedIds, setSelectedIds] = createSignal<Set<string>>(new Set(), { equals: false });
  const [lastSelectedId, setLastSelectedId] = createSignal<string | null>(null);
  const [groupingFiles, setGroupingFiles] = createSignal<AudioFile[] | null>(null);
  let panelElement: HTMLDivElement | undefined;
  const panelMenu = createContextMenu((): ContextMenuItem[] => [
    {
      label: "Select",
      icon: "ph:checks",
      onSelect: () => enterSelectMode(),
    },
  ]);

  const selectedFiles = () => files().filter((file) => selectedIds().has(file.id));

  createEffect(() => {
    if (!selectMode()) return;

    function onKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") exitSelectMode();
    }

    function onPointerDown(event: PointerEvent) {
      if (panelElement?.contains(event.target as Node)) return;
      exitSelectMode();
    }

    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("pointerdown", onPointerDown);
    onCleanup(() => {
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("pointerdown", onPointerDown);
    });
  });

  async function upload() {
    const file = await importAudioFile();
    if (!file) return;
    if (!isSupportedAudioFileName(file.name) && !isSupportedAudioFileName(file.path)) {
      await appAlert(`Unsupported audio file. Supported formats: ${SUPPORTED_AUDIO_IMPORT_LABEL}.`);
      return;
    }
    useAudioFileStore.getState().addFile(file);
  }

  function enterSelectMode(fileId?: string) {
    setSelectMode(true);
    if (fileId) {
      setSelectedIds(new Set([fileId]));
      setLastSelectedId(fileId);
    }
  }

  function exitSelectMode() {
    setSelectMode(false);
    setSelectedIds(new Set<string>());
    setLastSelectedId(null);
  }

  function selectFile(fileId: string, shiftKey: boolean) {
    setSelectMode(true);
    const current = selectedIds();
    if (shiftKey && lastSelectedId()) {
      const start = files().findIndex((file) => file.id === lastSelectedId());
      const end = files().findIndex((file) => file.id === fileId);
      if (start >= 0 && end >= 0) {
        const [lo, hi] = start < end ? [start, end] : [end, start];
        setSelectedIds(new Set([...current, ...files().slice(lo, hi + 1).map((file) => file.id)]));
        setLastSelectedId(fileId);
        return;
      }
    }

    const next = new Set(current);
    if (next.has(fileId)) next.delete(fileId);
    else next.add(fileId);
    setSelectedIds(next);
    setLastSelectedId(fileId);
  }

  function deleteSelected() {
    for (const file of selectedFiles()) useAudioFileStore.getState().removeFile(file.id);
    exitSelectMode();
  }

  function groupSelected() {
    if (selectedFiles().length === 0) return;
    setGroupingFiles(selectedFiles());
  }

  return (
    <div ref={panelElement} class={styles.panel} onContextMenu={panelMenu.onContextMenu}>
      <SectionRibbon
        title="Audio Files"
        expanded={props.expanded}
        onToggle={props.onToggle}
        showToggle={false}
        onContextMenu={panelMenu.onContextMenu}
        actions={(
          <HoverInfo content={`Upload ${SUPPORTED_AUDIO_IMPORT_LABEL}`}>
            <SectionRibbonActionButton onClick={() => void upload()} aria-label="Upload audio file">
              <Icon name="ph:plus" size={16} decorative />
            </SectionRibbonActionButton>
          </HoverInfo>
        )}
      />
      <Show when={selectMode() && props.expanded}>
        <div class={styles.selectionBar}>
          <Button size="xs" disabled={selectedFiles().length === 0} onClick={deleteSelected}>
            Delete
          </Button>
          <Button size="xs" disabled={selectedFiles().length === 0} onClick={groupSelected}>
            Group
          </Button>
          <span class={styles.selectionCount}>{selectedFiles().length}</span>
        </div>
      </Show>

      <ul class={`${styles.list} ${props.expanded ? styles.listOpen : ""}`} aria-hidden={!props.expanded}>
        <Show when={files().length === 0}>
          <li class={styles.empty}>No audio files yet.</li>
        </Show>
        <For each={files()}>
          {(file) => (
            <AudioFileItem
              file={file}
              selectMode={selectMode()}
              selected={selectedIds().has(file.id)}
              onSelect={(event) => selectFile(file.id, event.shiftKey)}
              onEnterSelectMode={() => enterSelectMode(file.id)}
              onRemove={() => useAudioFileStore.getState().removeFile(file.id)}
            />
          )}
        </For>
      </ul>
      {panelMenu.menu()}
      <Show when={groupingFiles()}>
        {(currentGroupingFiles) => (
          <ImportInstrumentModalSolid
            initialFiles={currentGroupingFiles()}
            onImportedFiles={(imported) => {
              for (const file of imported) useAudioFileStore.getState().removeFile(file.id);
              exitSelectMode();
            }}
            onClose={() => setGroupingFiles(null)}
          />
        )}
      </Show>
    </div>
  );
}

interface AudioFileItemProps {
  file: AudioFile;
  selectMode: boolean;
  selected: boolean;
  onSelect: (event: MouseEvent) => void;
  onEnterSelectMode: () => void;
  onRemove: () => void;
}

function AudioFileItem(props: AudioFileItemProps) {
  const menu = createContextMenu((): ContextMenuItem[] => [
    {
      label: "Select",
      icon: "ph:checks",
      onSelect: props.onEnterSelectMode,
    },
    {
      label: "Delete",
      icon: "ph:trash",
      onSelect: props.onRemove,
      separatorBefore: true,
    },
  ]);

  function onDragStart(event: DragEvent) {
    event.dataTransfer?.setData("application/x-beat-audio-file", props.file.id);
    event.dataTransfer?.setData("text/plain", props.file.name);
    if (event.dataTransfer) event.dataTransfer.effectAllowed = "copy";
  }

  return (
    <RowItem
      className={`${styles.item} ${props.selected ? styles.itemSelected : ""} ${props.selectMode ? styles.itemSelecting : ""}`}
      reserveDragSlot={false}
      cursor={props.selectMode ? "pointer" : "grab"}
      draggable={!props.selectMode}
      onClick={(event) => {
        if (!props.selectMode) return;
        props.onSelect(event);
      }}
      onDragStart={onDragStart}
      onContextMenu={menu.onContextMenu}
      iconAriaHidden={!props.selectMode}
      icon={props.selectMode ? (
        <input
          class={styles.itemCheckbox}
          type="checkbox"
          checked={props.selected}
          readOnly
          onClick={(event) => {
            event.stopPropagation();
            props.onSelect(event);
          }}
          aria-label={`Select ${props.file.name}`}
        />
      ) : (
        <span class={styles.itemDot} aria-hidden>
          <Icon name="ph:dots-six-vertical" size={14} decorative />
        </span>
      )}
      name={props.file.name}
      action={(
        <HoverInfo content={formatDuration(props.file.durationSeconds)}>
          <span class={styles.itemMeta}>
            <Icon name="ph:waveform" size={14} decorative />
          </span>
        </HoverInfo>
      )}
    >
      {menu.menu()}
    </RowItem>
  );
}

function formatDuration(seconds: number) {
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}
