// frontend/src/components/Tag/Tag.tsx
import type { ComponentProps } from "react";
import styles from "./Tag.module.css";

export type TagProps = ComponentProps<"span">;

export function Tag({ className, children, ...props }: TagProps) {
  return (
    <span className={[styles.tag, className].filter(Boolean).join(" ")} {...props}>
      {children}
    </span>
  );
}

// frontend/src/solid-ui/Tag/Tag.solid.tsx
import { splitProps, type JSX } from "solid-js";
import styles from "./Tag.module.css";

export type TagProps = JSX.HTMLAttributes<HTMLSpanElement> & { className?: string; tone?: "default" | "zero" };

export function Tag(allProps: TagProps) {
  const [local, props] = splitProps(allProps, ["class", "className", "tone"]);
  return (
    <span class={[styles.tag, local.tone === "zero" && styles.zero, local.class, local.className].filter(Boolean).join(" ")} {...props} />
  );
}
