// frontend/src/components/ActionFooter/ActionFooter.tsx
import { type HTMLAttributes, type ReactNode } from "react";
import styles from "./ActionFooter.module.css";

interface ActionFooterProps extends HTMLAttributes<HTMLElement> {
  align?: "start" | "end";
  children: ReactNode;
}

export function ActionFooter({ align = "end", className, children, ...rest }: ActionFooterProps) {
  const cls = [styles.footer, align === "start" && styles.start, className].filter(Boolean).join(" ");
  return (
    <footer className={cls} {...rest}>
      {children}
    </footer>
  );
}

// frontend/src/solid-ui/ActionFooter/ActionFooter.solid.tsx
import { splitProps, type JSX } from "solid-js";
import styles from "./ActionFooter.module.css";

export interface ActionFooterProps extends JSX.HTMLAttributes<HTMLElement> {
  align?: "start" | "end";
  className?: string;
}

export function ActionFooter(allProps: ActionFooterProps) {
  const [local, props] = splitProps(allProps, ["align", "class", "className", "children"]);
  const cls = () => [
    styles.footer,
    local.align === "start" && styles.start,
    local.class,
    local.className,
  ].filter(Boolean).join(" ");

  return (
    <footer class={cls()} {...props}>
      {local.children}
    </footer>
  );
}
