// frontend/src/features/Tracks/SegmentDrumPreview.tsx
import type { Segment } from "../../state/types";
import { drumStepOn } from "../../state/drumSteps";
import styles from "./SegmentDrumPreview.module.css";

interface Props {
  segment: Segment;
  displayLengthBeats?: number;
}

export function SegmentDrumPreview({ segment, displayLengthBeats }: Props) {
  if (segment.payload.kind !== "drum") return null;
  const { rows, stepCount } = segment.payload;
  if (rows.length === 0 || stepCount <= 0) return null;
  const viewLen = Math.max(0.001, displayLengthBeats ?? segment.lengthBeats);
  const stepBeats = segment.lengthBeats / stepCount;

  return (
    <svg className={styles.svg} viewBox={`0 0 ${viewLen} 100`} preserveAspectRatio="none" aria-hidden>
      {rows.map((row, rowIdx) => {
        const rowH = 100 / rows.length;
        const rowTop = rowIdx * rowH;
        return row.steps.slice(0, stepCount).map((step, stepIdx) => {
          if (!drumStepOn(step)) return null;
          const cellX = stepIdx * stepBeats;
          const cellW = stepBeats;
          if (cellX >= viewLen) return null;
          const markerW = Math.max(0.025, Math.min(cellW * 0.16, 0.08));
          return (
            <rect
              key={`${row.id}:${stepIdx}`}
              x={Math.min(viewLen - markerW, cellX + cellW * 0.5 - markerW * 0.5)}
              y={rowTop + rowH * 0.22}
              width={markerW}
              height={Math.max(2.5, rowH * 0.56)}
              className={styles.hit}
            />
          );
        });
      })}
    </svg>
  );
}

// frontend/src/features/Tracks/solid/SegmentDrumPreview.solid.tsx
import { For, Show } from "solid-js";
import { drumStepOn } from "../../../state/drumSteps";
import type { Segment } from "../../../state/types";
import styles from "../SegmentDrumPreview.module.css";

interface Props {
  segment: Segment;
  displayLengthBeats?: number;
}

export function SegmentDrumPreviewSolid(props: Props) {
  const drumPayload = () => props.segment.payload.kind === "drum" ? props.segment.payload : null;
  const viewLength = () => Math.max(0.001, props.displayLengthBeats ?? props.segment.lengthBeats);
  const stepBeats = () => {
    const payload = drumPayload();
    return payload ? props.segment.lengthBeats / payload.stepCount : 0;
  };

  return (
    <Show when={drumPayload()}>
      {(payload) => (
        <Show when={payload().rows.length > 0 && payload().stepCount > 0}>
          <svg class={styles.svg} viewBox={`0 0 ${viewLength()} 100`} preserveAspectRatio="none" aria-hidden="true">
            <For each={payload().rows}>
              {(row, rowIndex) => {
                const rowHeight = 100 / payload().rows.length;
                const rowTop = rowIndex() * rowHeight;
                return (
                  <For each={row.steps.slice(0, payload().stepCount)}>
                    {(step, stepIndex) => {
                      if (!drumStepOn(step)) return null;
                      const cellX = stepIndex() * stepBeats();
                      if (cellX >= viewLength()) return null;
                      const markerWidth = Math.max(0.025, Math.min(stepBeats() * 0.16, 0.08));
                      return (
                        <rect
                          x={Math.min(viewLength() - markerWidth, cellX + stepBeats() * 0.5 - markerWidth * 0.5)}
                          y={rowTop + rowHeight * 0.22}
                          width={markerWidth}
                          height={Math.max(2.5, rowHeight * 0.56)}
                          class={styles.hit}
                        />
                      );
                    }}
                  </For>
                );
              }}
            </For>
          </svg>
        </Show>
      )}
    </Show>
  );
}
