// frontend/src/solid-ui/NumberInput/NumberInput.solid.tsx
import { createEffect, createSignal, Show } from "solid-js";
import styles from "../../components/NumberInput/NumberInput.module.css";

export interface NumberInputProps {
  value: number;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  label?: string;
  layout?: "stacked" | "inline";
  commitOnChange?: boolean;
  maxLength?: number;
  onChange: (v: number) => void;
}

export function NumberInput(props: NumberInputProps) {
  const [text, setText] = createSignal(String(props.value));
  const [editing, setEditing] = createSignal(false);

  createEffect(() => {
    if (editing()) return;
    setText(String(props.value));
  });

  function commit(raw: string) {
    const parsed = parseFloat(raw);
    if (Number.isNaN(parsed)) {
      setText(String(props.value));
      return;
    }
    const clamped = Math.max(props.min ?? -Infinity, Math.min(props.max ?? Infinity, parsed));
    props.onChange(clamped);
    setText(String(clamped));
  }

  function updateText(raw: string) {
    setText(raw);
    if (!props.commitOnChange) return;
    const parsed = parseFloat(raw);
    if (Number.isNaN(parsed)) return;
    props.onChange(Math.max(props.min ?? -Infinity, Math.min(props.max ?? Infinity, parsed)));
  }

  function onKeyDown(event: KeyboardEvent) {
    if (event.key === "ArrowUp") {
      event.preventDefault();
      commit(String(props.value + (event.shiftKey ? (props.step ?? 1) * 10 : props.step ?? 1)));
    } else if (event.key === "ArrowDown") {
      event.preventDefault();
      commit(String(props.value - (event.shiftKey ? (props.step ?? 1) * 10 : props.step ?? 1)));
    } else if (event.key === "Enter") {
      (event.target as HTMLInputElement).blur();
    }
  }

  return (
    <label class={`${styles.wrap} ${props.layout === "inline" ? styles.inline : ""}`}>
      <Show when={props.label}>
        <span class={styles.label}>{props.label}</span>
      </Show>
      <span class={styles.fieldFrame}>
        <input
          class={styles.input}
          type="text"
          inputMode="numeric"
          maxLength={props.maxLength}
          value={text()}
          onInput={(event) => updateText(event.currentTarget.value)}
          onFocus={() => setEditing(true)}
          onBlur={(event) => {
            setEditing(false);
            commit(event.currentTarget.value);
          }}
          onKeyDown={onKeyDown}
        />
        <Show when={props.unit}>
          <span class={styles.unit}>{props.unit}</span>
        </Show>
      </span>
    </label>
  );
}

// frontend/src/components/NumberInput/NumberInput.tsx
import { useEffect, useState, type ChangeEvent, type KeyboardEvent } from "react";
import styles from "./NumberInput.module.css";

export interface NumberInputProps {
  value: number;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  label?: string;
  layout?: "stacked" | "inline";
  commitOnChange?: boolean;
  maxLength?: number;
  onChange: (v: number) => void;
}

/**
 * NumberInput — a single-line numeric field with arrow-key step and clamp.
 * Visual: black bg, white text, 1px white frame (legitimate — input frame
 * counts as structure delineation).
 */
export function NumberInput({
  value,
  min = -Infinity,
  max = Infinity,
  step = 1,
  unit,
  label,
  layout = "stacked",
  commitOnChange = false,
  maxLength,
  onChange,
}: NumberInputProps) {
  const [text, setText] = useState(String(value));
  const [editing, setEditing] = useState(false);

  useEffect(() => {
    if (editing) return;
    setText(String(value));
  }, [editing, value]);

  function commit(raw: string) {
    const n = parseFloat(raw);
    if (Number.isNaN(n)) {
      setText(String(value));
      return;
    }
    const clamped = Math.max(min, Math.min(max, n));
    onChange(clamped);
    setText(String(clamped));
  }

  function updateText(raw: string) {
    setText(raw);
    if (!commitOnChange) return;
    const n = parseFloat(raw);
    if (Number.isNaN(n)) return;
    onChange(Math.max(min, Math.min(max, n)));
  }

  function onKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (e.key === "ArrowUp") {
      e.preventDefault();
      const delta = e.shiftKey ? step * 10 : step;
      commit(String(value + delta));
    } else if (e.key === "ArrowDown") {
      e.preventDefault();
      const delta = e.shiftKey ? step * 10 : step;
      commit(String(value - delta));
    } else if (e.key === "Enter") {
      (e.target as HTMLInputElement).blur();
    }
  }

  return (
    <label className={`${styles.wrap} ${layout === "inline" ? styles.inline : ""}`}>
      {label && <span className={styles.label}>{label}</span>}
      <span className={styles.fieldFrame}>
        <input
          className={styles.input}
          type="text"
          inputMode="numeric"
          maxLength={maxLength}
          value={text}
          onChange={(e: ChangeEvent<HTMLInputElement>) => updateText(e.target.value)}
          onFocus={() => setEditing(true)}
          onBlur={(e) => {
            setEditing(false);
            commit(e.currentTarget.value);
          }}
          onKeyDown={onKeyDown}
        />
        {unit && <span className={styles.unit}>{unit}</span>}
      </span>
    </label>
  );
}
