// frontend/src/solid-ui/NumberInput/NumberInput.demo.solid.tsx
import { createSignal } from "solid-js";
import { NumberInput } from "./NumberInput.solid";

export function NumberInputDemo() {
  const [value, setValue] = createSignal(60);
  return (
    <section>
      <h2>Solid NumberInput</h2>
      <NumberInput label="Cut" value={value()} min={0} max={100} unit="%" onChange={setValue} />
      <NumberInput
        layout="inline"
        label="Fine"
        value={value() / 100}
        min={0}
        max={1}
        step={0.01}
        commitOnChange
        onChange={(next) => setValue(Math.round(next * 100))}
      />
      <NumberInput layout="editor" label="BPM" value={value()} min={20} max={999} step={1} onChange={setValue} />
    </section>
  );
}

// frontend/src/components/NumberInput/NumberInput.demo.tsx
import { useState } from "react";
import { DemoGrid, DemoSample, DemoSection } from "../../design/UiKitDemo";
import { NumberInput } from "./NumberInput";

export function NumberInputDemo() {
  const [bpm, setBpm] = useState(132);
  const [gain, setGain] = useState(-6);

  return (
    <DemoSection title="NumberInput" note="Numeric fields clamp, commit, and support arrow-key stepping.">
      <DemoGrid>
        <DemoSample label="stacked">
          <NumberInput label="Tempo" value={bpm} min={20} max={300} step={1} unit="bpm" onChange={setBpm} />
        </DemoSample>
        <DemoSample label="inline">
          <NumberInput label="Gain" value={gain} min={-48} max={24} step={0.5} unit="dB" layout="inline" onChange={setGain} />
        </DemoSample>
      </DemoGrid>
    </DemoSection>
  );
}
