// frontend/src/components/Modal/Modal.tsx
import { useEffect, useId, useRef, type ReactNode } from "react";
import { createPortal } from "react-dom";
import styles from "./Modal.module.css";
import { Icon } from "../Icon";
import { useModalStack } from "./modalStack";

export interface ModalProps {
  open: boolean;
  title: ReactNode;
  /** Optional subtitle under the title in the header stripe. */
  subtitle?: string;
  /** Footer content. Typically a row of Buttons; see ConfirmDialog for presets. */
  footer?: ReactNode;
  /** Removes default body padding for editors that provide their own internal spacing. */
  flushBody?: boolean;
  /** Optional compact controls rendered in the title ribbon. */
  headerActions?: ReactNode;
  /** When true, clicking the backdrop requests close. Defaults off to avoid losing editor work. */
  closeOnScrimClick?: boolean;
  /** When true, Escape requests close. Defaults off so Escape can cancel tools/modes inside editors. */
  closeOnEscape?: boolean;
  /** Width preset. */
  width?: "sm" | "md" | "lg" | "full";
  /** Stable id for modal stack coordination and contextual hotkeys. */
  scopeId?: string;
  /** Should the modal track dirty state and prompt on close? */
  dirty?: boolean;
  /** Called when the user requests close (X, escape, or a footer cancel). */
  onClose: () => void;
  /** Optional handler invoked when the user requests close while `dirty`. */
  onRequestCloseDirty?: () => void;
  children: ReactNode;
}

/**
 * Modal — the universal floating panel.
 *
 * - Animates in from the bottom (slide).
 * - Backdrop scrim. Clicking the scrim requests close.
 * - Multiple modals stack via the modalStack registry; the stacking order
 *   determines z-index, and the unsaved-check overlay (rendered by
 *   <ModalStackOverlay/>) shadows everything when triggered.
 */
export function Modal({
  open,
  title,
  subtitle,
  footer,
  flushBody = false,
  headerActions,
  closeOnScrimClick = false,
  closeOnEscape = false,
  width = "md",
  scopeId,
  dirty = false,
  onClose,
  onRequestCloseDirty,
  children,
}: ModalProps) {
  const autoId = useId();
  const id = scopeId ?? autoId;
  const ref = useRef<HTMLDivElement>(null);
  const { push, pop, indexOf } = useModalStack();

  useEffect(() => {
    if (!open) return;
    push(id);
    return () => pop(id);
  }, [open, id, push, pop]);

  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (closeOnEscape && e.key === "Escape") {
        e.stopPropagation();
        requestClose();
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, dirty, closeOnEscape]);

  function requestClose() {
    if (dirty && onRequestCloseDirty) {
      onRequestCloseDirty();
    } else {
      onClose();
    }
  }

  if (!open) return null;

  const stackIndex = indexOf(id);

  return createPortal(
    <div
      className={styles.scrim}
      style={{ zIndex: 3000 + stackIndex * 10 }}
      data-floating-layer
      onMouseDown={(e) => {
        if (closeOnScrimClick && e.target === e.currentTarget) requestClose();
      }}
    >
      <div
        ref={ref}
        className={`${styles.modal} ${styles[`width-${width}`]} animate-slide-in-bottom`}
        role="dialog"
        aria-modal="true"
        aria-labelledby={`${id}-title`}
        data-floating-layer
      >
        <header className={styles.header}>
          <div className={styles.titleGroup}>
            <h2 id={`${id}-title`} className={styles.title}>
              {title}
            </h2>
            {subtitle && <p className={styles.subtitle}>{subtitle}</p>}
          </div>
          <div className={styles.headerRight}>
            {headerActions && <div className={styles.headerActions}>{headerActions}</div>}
            <button
              className={styles.closeBtn}
              onClick={requestClose}
              aria-label="Close"
              type="button"
            >
              <Icon name="ph:x" size={16} decorative />
            </button>
          </div>
        </header>

        <div className={`${styles.body} ${flushBody ? styles.bodyFlush : ""}`}>{children}</div>

        {footer && <footer className={styles.footer}>{footer}</footer>}
      </div>
    </div>,
    document.body,
  );
}

// frontend/src/solid-ui/Modal/Modal.solid.tsx
import { createEffect, createUniqueId, onCleanup, Show, type JSX } from "solid-js";
import { Portal } from "solid-js/web";
import { Icon } from "../Icon";
import { useModalStack } from "./modalStack";
import styles from "./Modal.module.css";

export interface ModalProps {
  open: boolean;
  title: JSX.Element;
  subtitle?: string;
  footer?: JSX.Element;
  flushBody?: boolean;
  headerActions?: JSX.Element;
  closeOnScrimClick?: boolean;
  closeOnEscape?: boolean;
  width?: "sm" | "md" | "lg" | "editor" | "full";
  scopeId?: string;
  dirty?: boolean;
  onClose: () => void;
  onRequestCloseDirty?: () => void;
  children: JSX.Element;
}

export function Modal(allProps: ModalProps) {
  const props = allProps;
  const autoId = createUniqueId();
  const id = () => props.scopeId ?? autoId;
  const width = () => props.width ?? "md";

  createEffect(() => {
    if (!props.open) return;
    const modalId = id();
    useModalStack.getState().push(modalId);
    onCleanup(() => useModalStack.getState().pop(modalId));
  });

  createEffect(() => {
    if (!props.open || !props.closeOnEscape) return;
    function onKey(event: KeyboardEvent) {
      if (event.key !== "Escape") return;
      event.stopPropagation();
      requestClose();
    }
    window.addEventListener("keydown", onKey);
    onCleanup(() => window.removeEventListener("keydown", onKey));
  });

  function requestClose() {
    if (props.dirty && props.onRequestCloseDirty) {
      props.onRequestCloseDirty();
      return;
    }
    props.onClose();
  }

  return (
    <Show when={props.open}>
      <Portal mount={document.body}>
        <div
          class={styles.scrim}
          style={{ "z-index": 3000 }}
          data-floating-layer
          onMouseDown={(event) => {
            if (props.closeOnScrimClick && event.target === event.currentTarget) requestClose();
          }}
        >
          <div
            class={`${styles.modal} ${styles[`width-${width()}`]} animate-slide-in-bottom`}
            role="dialog"
            aria-modal="true"
            aria-labelledby={`${id()}-title`}
            data-floating-layer
          >
            <header class={styles.header}>
              <div class={styles.titleGroup}>
                <h2 id={`${id()}-title`} class={styles.title}>
                  {props.title}
                </h2>
                <Show when={props.subtitle}><p class={styles.subtitle}>{props.subtitle}</p></Show>
              </div>
              <div class={styles.headerRight}>
                <Show when={props.headerActions}><div class={styles.headerActions}>{props.headerActions}</div></Show>
                <button class={styles.closeBtn} onClick={requestClose} aria-label="Close" type="button">
                  <Icon name="ph:x" size={16} decorative />
                </button>
              </div>
            </header>

            <div class={`${styles.body} ${props.flushBody ? styles.bodyFlush : ""}`}>{props.children}</div>

            <Show when={props.footer}><footer class={styles.footer}>{props.footer}</footer></Show>
          </div>
        </div>
      </Portal>
    </Show>
  );
}
