// frontend/src/solid-ui/SectionRibbon/SectionRibbon.solid.tsx
import { Show, splitProps, type JSX } from "solid-js";
import { Button } from "../Button";
import { Icon } from "../Icon";
import { Tag } from "../Tag";
import styles from "./SectionRibbon.module.css";

export interface SectionRibbonProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, "title"> {
  title: string;
  expanded: boolean;
  onToggle: () => void;
  actions?: JSX.Element;
  count?: number;
  showToggle?: boolean;
  className?: string;
}

export function SectionRibbon(allProps: SectionRibbonProps) {
  const [local, props] = splitProps(allProps, ["title", "expanded", "onToggle", "actions", "count", "showToggle", "class", "className"]);
  const showToggle = () => local.showToggle ?? true;
  return (
    <div
      class={[
        styles.ribbon,
        local.expanded && styles.ribbonExpanded,
        !showToggle() && styles.ribbonNoToggle,
        local.class,
        local.className,
      ].filter(Boolean).join(" ")}
      {...props}
    >
      <Show when={showToggle()}>
        <Button
          iconOnly
          size="md"
          class={styles.toggle}
          onClick={local.onToggle}
          aria-label={local.expanded ? `Collapse ${local.title}` : `Expand ${local.title}`}
        >
          <Icon name={local.expanded ? "ph:caret-down" : "ph:caret-right"} size={16} decorative />
        </Button>
      </Show>
      <span class={styles.label}>{local.title}</span>
      <span class={styles.right}>
        <Show when={typeof local.count === "number"}>
          <span class={styles.count}><Tag tone={local.count === 0 ? "zero" : "default"}>{local.count}</Tag></span>
        </Show>
        <Show when={local.actions}><span class={styles.actions}>{local.actions}</span></Show>
      </span>
    </div>
  );
}

export function SectionRibbonActionButton(allProps: Omit<Parameters<typeof Button>[0], "iconOnly" | "size"> & { className?: string }) {
  const [local, props] = splitProps(allProps, ["class", "className"]);
  return (
    <Button
      iconOnly
      size="md"
      class={[styles.actionButton, local.class, local.className].filter(Boolean).join(" ")}
      {...props}
    />
  );
}

// frontend/src/components/SectionRibbon/SectionRibbon.tsx
import { forwardRef, type ComponentProps, type ReactNode } from "react";
import { Button } from "../Button";
import { Icon } from "../Icon";
import { Tag } from "../Tag";
import styles from "./SectionRibbon.module.css";

interface SectionRibbonProps {
  title: string;
  expanded: boolean;
  onToggle: () => void;
  className?: string;
  actions?: ReactNode;
  count?: number;
  showToggle?: boolean;
  onContextMenu?: React.MouseEventHandler<HTMLDivElement>;
}

export function SectionRibbon({
  title,
  expanded,
  onToggle,
  className,
  actions,
  count,
  showToggle = true,
  onContextMenu,
}: SectionRibbonProps) {
  return (
    <div
      className={`${styles.ribbon} ${expanded ? styles.ribbonExpanded : ""} ${!showToggle ? styles.ribbonNoToggle : ""} ${className ?? ""}`}
      onContextMenu={onContextMenu}
    >
      {showToggle && (
        <Button
          iconOnly
          size="md"
          className={styles.toggle}
          onClick={onToggle}
          aria-label={expanded ? `Collapse ${title}` : `Expand ${title}`}
        >
          <Icon name={expanded ? "ph:caret-down" : "ph:caret-right"} size={16} decorative />
        </Button>
      )}
      <span className={styles.label}>{title}</span>
      <span className={styles.right}>
        {typeof count === "number" && (
          <span className={styles.count}>
            <Tag>{count}</Tag>
          </span>
        )}
        {actions && <span className={styles.actions}>{actions}</span>}
      </span>
    </div>
  );
}

export const SectionRibbonActionButton = forwardRef<
  HTMLButtonElement,
  Omit<ComponentProps<typeof Button>, "iconOnly" | "size">
>(function SectionRibbonActionButton({ children, className, ...props }, ref) {
  return (
    <Button
      ref={ref}
      iconOnly
      size="md"
      className={[styles.actionButton, className].filter(Boolean).join(" ")}
      {...props}
    >
      {children}
    </Button>
  );
});
