// frontend/src/features/InstrumentEditor/WaveformPicker.tsx
import { Icon, HoverInfo } from "../../components";
import type { Instrument } from "../../state/types";
import styles from "./WaveformPicker.module.css";

type Waveform = Instrument["waveform"];

interface Option {
  value: Waveform;
  icon: string;
  label: string;
}

const OPTIONS: Option[] = [
  { value: "sine",     icon: "ph:wave-sine",      label: "Sine"     },
  { value: "saw",      icon: "ph:wave-sawtooth",  label: "Saw"      },
  { value: "square",   icon: "ph:wave-square",    label: "Square"   },
  { value: "triangle", icon: "ph:wave-triangle",  label: "Triangle" },
  { value: "noise",    icon: "ph:waveform",       label: "Noise"    },
];

export interface WaveformPickerProps {
  value: Waveform;
  /** When true, "sample" appears as an extra option (hybrid only). */
  allowSample?: boolean;
  /** When true, "wavetable" appears as an extra option (Aether WT only). */
  allowWavetable?: boolean;
  onChange: (v: Waveform) => void;
}

/**
 * WaveformPicker — radio-group of icon buttons, one per waveform shape.
 *
 * The selected option is filled (inverted bg). Hovering the selected option
 * dims it to the off-white token, matching the rest of the active-surface
 * hover rule. Hovering an unselected option color-inverts as usual.
 */
export function WaveformPicker({ value, allowSample, allowWavetable, onChange }: WaveformPickerProps) {
  const opts = [
    ...OPTIONS,
    ...(allowSample ? [{ value: "sample" as Waveform, icon: "ph:music-notes-simple", label: "Sample" }] : []),
    ...(allowWavetable ? [{ value: "wavetable" as Waveform, icon: "ph:waveform", label: "Wavetable" }] : []),
  ];
  const selected = opts.find((o) => o.value === value);

  return (
    <div className={styles.wrap}>
      <div className={styles.row} role="radiogroup" aria-label="Waveform">
        {opts.map((o) => (
          <HoverInfo key={o.value} content={o.label}>
            <button
              type="button"
              role="radio"
              aria-checked={value === o.value}
              aria-label={o.label}
              className={`${styles.btn} ${value === o.value ? styles.active : ""}`}
              onClick={() => onChange(o.value)}
            >
              <Icon name={o.icon} size={16} decorative />
            </button>
          </HoverInfo>
        ))}
      </div>
      <div className={styles.selectedLabel}>{selected?.label ?? value}</div>
    </div>
  );
}

// frontend/src/features/InstrumentEditor/WaveformPicker.solid.tsx
import { createMemo, For, type Accessor } from "solid-js";
import { HoverInfo, Icon } from "../../solid-ui";
import type { Instrument } from "../../state/types";
import styles from "./WaveformPicker.module.css";

type Waveform = Instrument["waveform"];

interface Option {
  value: Waveform;
  icon: string;
  label: string;
}

const OPTIONS: Option[] = [
  { value: "sine", icon: "ph:wave-sine", label: "Sine" },
  { value: "saw", icon: "ph:wave-sawtooth", label: "Saw" },
  { value: "square", icon: "ph:wave-square", label: "Square" },
  { value: "triangle", icon: "ph:wave-triangle", label: "Triangle" },
  { value: "noise", icon: "ph:waveform", label: "Noise" },
];

export interface WaveformPickerProps {
  value: Waveform;
  allowSample?: boolean;
  allowWavetable?: boolean;
  onChange: (value: Waveform) => void;
}

export function WaveformPicker(props: WaveformPickerProps) {
  return <WaveformPickerRuntime state={() => props} />;
}

function WaveformPickerRuntime(props: { state: Accessor<WaveformPickerProps> }) {
  const opts = createMemo(() => [
    ...OPTIONS,
    ...(props.state().allowSample ? [{ value: "sample" as Waveform, icon: "ph:music-notes-simple", label: "Sample" }] : []),
    ...(props.state().allowWavetable ? [{ value: "wavetable" as Waveform, icon: "ph:waveform", label: "Wavetable" }] : []),
  ]);
  const selected = createMemo(() => opts().find((option) => option.value === props.state().value));

  return (
    <div class={styles.wrap}>
      <div class={styles.row} role="radiogroup" aria-label="Waveform">
        <For each={opts()}>
          {(option) => (
            <HoverInfo content={option.label}>
              <button
                type="button"
                role="radio"
                aria-checked={props.state().value === option.value}
                aria-label={option.label}
                class={`${styles.btn} ${props.state().value === option.value ? styles.active : ""}`}
                onClick={() => props.state().onChange(option.value)}
              >
                <Icon name={option.icon} size={16} decorative />
              </button>
            </HoverInfo>
          )}
        </For>
      </div>
      <div class={styles.selectedLabel}>{selected()?.label ?? props.state().value}</div>
    </div>
  );
}
